spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogs?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456


logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log

server:
  port: 8080

